name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10'
         
     - uses: actions/cache@v3
       with:
         path: |
           venv
           ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-

     - name: Install dependencies
       run: |
         python -m venv venv
         source venv/bin/activate
         pip install -r requirements.txt
         playwright install

     - name: Run tests
       run: |
         source venv/bin/activate
         pytest tests/unit/ --cov=src --junitxml=test-results/junit.xml
         pytest tests/integration/
         pytest tests/e2e/