name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10'
         
     - uses: actions/cache@v3
       with:
         path: |
           venv
           ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-

     - name: Install dependencies
       run: |
         python -m venv venv
         source venv/bin/activate
         pip install -r requirements.txt
         playwright install

     - name: Run tests
       run: |
         source venv/bin/activate
         pytest tests/unit/ --cov=src --junitxml=test-results/junit.xml
         pytest tests/integration/
         pytest tests/e2e/
         
  security:
   needs: test
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     
     - name: Build image
       run: docker build -t app:test .
     
     - name: Run Trivy vulnerability scanner
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: 'app:test'
         format: 'table'
         exit-code: '1'
         ignore-unfixed: true
         severity: 'CRITICAL,HIGH'